# Copyright (C) 2020-2022, TomTom (http://tomtom.com).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Keepachangelog Manager'
author: 'Kevin de Jong'
description: >
  Setup a release workflow based around your `CHANGELOG.md`

branding:
  icon: 'book'  
  color: 'blue'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: true
  
  publish:
    description: '(Optional) Release your CHANGELOG.md using GitHub Releases'
    default: false
    required: false

  tag:
    description: '(Optional) Tag format'
    default: '{version}'
    required: false

  release-name:
    description: '(Optional) GitHub Release format'
    default: 'Release {tag}'
    required: false

  commit-message:
    description: '(Optional) Commit message format'
    default: "docs(release): update CHANGELOG.md for '{release-name}'"
    required: false

outputs:
  version:
    description: 'The version of the released CHANGELOG.md'

runs:
  using: 'node16'
  main: 'dist/index.js'
